
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 17

[keyboard]
bindings = [{ key = "F12", action = "ToggleFullscreen" }]

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = [
	"-l", 
	"-c", 
	"source ~/.zshrc; tmux attach || tmux"
]

# For my Linux i3wm setup
#[terminal.shell]
#program = "/bin/bash"
#args = [
#	"-l",
#	"-c",
#	"source ~/.bashrc; tmux new-session"
#]

