
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 5
padding.y = 0
opacity = 0.9
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12

[keyboard]
bindings = [{ key = "F12", action = "ToggleFullscreen" }]

[general]
# Check README at https://github.com/catppuccin/alacritty
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal.shell]
program = "fish"
args = ["-l"]
