
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12

[keyboard]
bindings = [{ key = "F12", action = "ToggleFullscreen" }]

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]

[terminal.shell]
program = "fish"
args = ["-l"]
